version: '3.7'

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    networks:
        - wordpress-network
    ports:
        - "4444:4444"

  chrome:
    image: selenium/node-chrome
    container_name: selenium-chrome
    networks:
        - wordpress-network
    volumes:
        - /dev/shm:/dev/shm
    depends_on:
        - selenium-hub
    environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox
    container_name: selenium-firefox
    networks:
        - wordpress-network
    volumes:
        - /dev/shm:/dev/shm
    depends_on:
        - selenium-hub
    environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444

networks:
    wordpress-network:
        external: true
        name: wp-net
