version: '3.7'

services:
    my-wpdb:
        command: '--default-authentication-plugin=mysql_native_password'
        container_name: mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: KL.JKK922
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wp-user
            MYSQL_PASSWORD: 090sdfsfSOIWER
        restart: always
        networks: 
            - wordpress-network
        volumes:
            - db_data:/var/lib/mysql

    my-wp:
        container_name: wordpress.local
        hostname: wordpress.local
        image: wordpress:latest
        volumes:
            - wordpress_files:/var/www/html
        ports:
            - "80:80"
        links:
            - my-wpdb:mysql
        environment:
            WORDPRESS_DB_HOST: my-wpdb:3306
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wp-user
            WORDPRESS_DB_PASSWORD: 090sdfsfSOIWER
        restart: always
        depends_on:
            - my-wpdb
        networks: 
            - wordpress-network

    phpmyadmin:
        hostname: phpmyadmin.local
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 127.0.0.1:8081:80
        links:
            - my-wpdb:db
        networks: 
            - wordpress-network

    selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        networks:
            - wordpress-network
        ports:
            - "4444:4444"

    chrome:
        image: selenium/node-chrome
        container_name: selenium-chrome
        networks:
            - wordpress-network
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    edge:
        image: selenium/node-edge
        container_name: selenium-edge
        networks:
            - wordpress-network
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    firefox:
        image: selenium/node-firefox
        container_name: selenium-firefox
        networks:
            - wordpress-network
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

networks:
    wordpress-network:
        driver: bridge
        name: wp-net

volumes:
    wordpress_files:
    db_data:
